name: Build & push Docker image

on:
  push:
    branches: ["main"]
    tags:
      - "v*.*.*" # also run when a version tag is pushed

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set image tag
        id: tag
        run: |
          # Use the git tag if present, otherwise fallback to "latest"
          TAG=${GITHUB_REF#refs/tags/}
          echo "tag=${TAG:-latest}" >> $GITHUB_OUTPUT

      - name: Build & push image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            sijosamdev/sijo-virtual-resume-docker:${{ steps.tag.outputs.tag }}
          platforms: linux/amd64
